--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.6
-- Dumped by pg_dump version 9.6.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET search_path = public, pg_catalog;

--
-- Data for Name: modules; Type: TABLE DATA; Schema: public; Owner: codrdb
--

COPY modules (id, name, description) FROM stdin;
1	The Pearls of Computer Science	In this module you will learn about seven ‘pearls’ of technical computer science, which will allow you to see how vast this subject is. The module deals with computer architecture, programming algorithms, encrypting information, developing software, the Internet as a computer network, functional programming and artificial intelligence. For this module's project, you and your project team will produce a system that automatically analyses and visualizes Tweets.\n
2	Software Systems	In the Software System module, you will learn how to design and build software, from analysing the requirements to delivering a working programme. For the final project, you will programme a multi-player game according to a fixed structure.
3	Network Systems	During the third module you will learn about computer networks. A good example of these networks is the Internet. How does this kind of network operate? In this module you will learn more about how information is sent and received in small packages, through cables or a wireless system, how the best path through a network is found and how you can prevent the packages from getting damaged or lost on the way. After that, it will be time to learn about a network's application, protection against abuse and the scalability of large networks. Various challenging assignments will help you absorb the knowledge you need.
4	Data & Information	In the last module of the first year, you will learn how to place relevant business information in a database. You will become familiar with data management concepts and relational databases. In this module you will also work on developing software using an approach that is quite common in the business world: Agile software engineering. In two-week ‘sprints’, you will work on delivering the software and in so-called ‘scrum sessions’ you will discuss with fellow students what you have been doing, what your plans are and what problems you are coming up against. It is a great way of learning how to work on software as a team and in a structured way.
5	Computer Systems	In this module you will learn how to realize digital circuits using Boolean algebra. With the help of these digital circuits you can develop the basic building blocks for a computer, such as adders and multipliers. You will learn about building standard processors according to the Von Neumann principle and also about Instruction Set Architecture (ISA), which allows you to programme these processes using a programming language. In this module you will programme ‘close to the hardware’. You will also learn how operating systems are built and how they work.
6	Intelligent Interaction Design	This module is about designing, realizing and evaluating interaction between people and technical systems. In your project, you will work in a multidisciplinary team with members from our Technical Computer Science, Business & IT and Creative Technology programmes. Your goal as a team will be to design an interactive – and possibly intelligent – system and to evaluate it with potential users. In addition to the team project, this muddle includes lectures, instructions and self-study. You will learn about statistics and get familiar with methods for conducting user studies. Quantitative and qualitative methods for analysing the resulting data are also on the menu. In the artificial intelligence part of the module, you will learn and apply various techniques for modelling intelligent system behaviour. Learning to reflect on scientific research in relation to the design and development of technology is also a part of the programme.
7	Discrete Structures & Efficient Algorithms	In this module you will grow familiar with mathematical structures, such as graphs, networks and languages, as well as basic algebraic structures, such as groups and fields. The focus will be on algorithmic questions connected to these discrete structures. This means data structures, formal languages and models for computation will be on the menu, too. 
8	Programming Paradigms	The standard style of programming follows the imperative paradigm: you tell the computer what it has to do step-by-step. But there are also some surprising alternatives to this, like the functional and logical paradigm. These are stronger and better suited for certain purposes. In this module, you will not only learn about these alternatives, you will also get a broader view and understanding of other programming language concepts, such as typification and semantics.
\.


--
-- Data for Name: courses; Type: TABLE DATA; Schema: public; Owner: codrdb
--

COPY courses (id, module_id, name, description) FROM stdin;
1	1	Pearl 000 - Black Pearl (Computer Architecture)	After absorbing the pearl “Computer Architecture”\n• The student can work with binary and hexadecimal number representations, binary logic and boolean algebra.\n• The student knows the basic architecture of a computer and its concepts register, memory, address, ALU, clock, program, program counter, instruction and mnemonic.\n• The student can write simple programs for a microcomputer in machine language using arithmetic, I/O, and (conditional) jump instructions.
2	1	Pearl 001 - Blue Pearl (Algoritmics)	After absorbing the pearl “Algoritmics”\n• The student can explain the importance of searching and sorting algorithms;\n• The student can explain the principle of and differences between linear and binary search methods, as well as between bubble sort and merge sort;\n• The student understands the complexity arguments behind the aforementioned algorithms and can analyse which is the best solution in what context;\n• The student can apply simple imperative programming concepts: if/then, while, integer variables and arrays;\n• The student can program the above algorithms in Python.
3	1	Pearl 010 - Green Pearl (Databases)	After absorbing the pearl “Databases”\n• The student knows the basic concepts of databases\n• The student can design a databaseschema for a simple case using ER-modeling.\n• The student can realize such a design in a relational DBMS using SQL.\n• The student can query and update a relational DBMS with SQL.
4	1	Pearl 011 - Cyan Pearl (Functional Programming)	After absorbing the pearl “Functional Programming”\n• The student knows the basic concepts of the chosen functional language,\n• The student is able to explain the concept of function application,\n• The student understands the principles of recursion and their relationship with induction,\n• The student is able to express simple algorithms in the chosen functional language.
5	2	Academic Skills	Concerning Academic Skills, after successfully finishing this module a student is capable of:\nDescribing the major principles of effective time management.\nApplying these principles to make a personal planning for a medium long term period, e.g., a study semester, and for a medium-sized project.\nFormulating personal strengths and weaknesses with regard to time management, study behaviour and project work.\nDescribing the major principles for defining a general project planning.\nApplying these principles when reflecting on some previous project planning.\nGiving and receiving peer feedback.\nIdentifying major personal pitfalls concerning procrastination behaviour.
6	2	Mathematics	Concerning Mathematics, after successfully finishing this module a student is capable of:\nWorking with limits and the definitions of continuity and differentiability and applications.\nInvestigating functions in two variables.\nWorking with elementary properties of integrals and calculate integrals using different techniques.\nWorking with power series and Taylor series.
7	2	Programming	Concerning Programming, after successfully finishing this module a student is capable of:\nExplaining and applying the core concepts of imperative programming, such as variables, data types, structured programming statements, recursion, lists, arrays, methods, parameters, and exceptions.\nExplaining and applying the core concepts of object-orientation, such as object, class, value, type, object reference, interface, specialisation / inheritance, and composition.\nUsing the Model/View/Controller pattern when developing applications.\nWriting simple multi-threaded programs, and explaining the operation and problems (race-conditions) of concurrent threads, and using synchronisation mechanisms, such as monitors, locks and wait  sets.\nWriting programs using basic network mechanisms, based on sockets.\nExplaining and applying the basic concepts of security engineering and applying them to Java programs.\nWriting software of average size (around ten classes) in Java,by using the concepts mentioned above, including the use ofalgorithms for searching and sorting data\nDocumenting software of this size, by using (informal)preconditions, postconditions and (class) invariants, and (informally) justifying the correctness of the implemented software.\nExplaining how this software can be tested, defining and executing a test plan, and measuring and improving test coverage. 
8	2	Software Design	Concerning Software Design, after successfully finishing this module a student is capable of:\nSpecifying an existing software system or a software system under design in terms of UML models (including class diagrams, activity diagrams and state machines).\nInterpreting these models, explaining the relation between different models, and between each model and the software code, and the usefulness of defining models in addition to writing software code.\nExplaining the commonly recognised phases of software development\nApplying version management in software development projects\nExplaining basic software metrics and using them to assess quality characteristics of a code base 
9	3	Mathematics	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
10	3	Academic Skills	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
11	3	Network Systems	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
12	4	Probability Theory	M1.    …explain and apply the use of elementary probability theory, such as combinatoric probability theory, conditional probability, independence;\nM2.    …explain and apply probability distributions of one or more random variables, (discrete) conditional probabilities, and compute expectation, variance, and correlation coefficient;\nM3.    …explain and apply basic discrete and continuous distributions, including binomial, geometric, Poisson, uniform, exponential and normal distributions.
13	4	Web Programming	P1.    …design and implement complex multi-tier web applications;\nP2.    …use repositories and version management;\nP3.    …integrate web applications with existing (REST-ful) services;\nP4.    …build user interfaces with frameworks for HTML, CSS, and javascript;\nP5.    …explain the consequences of server-side vs. client-side scripting, servlets, Ajax, JSP, Web frameworks, etc.;
14	4	Requirements Engineering	R1.    …identify business requirements and translate these to user stories;\nR2.    …specify functional and non-functional requirements;\nR3.    …prioritize requirements in collaboration with various stakeholders;\nR4.    …design a UML class diagram;\nR5.     …systematically design web based applications using UML;
15	5	Computer Architecture and Organisation	The architecture and organisation of computer systems are presented. Computer organisation deals with elementary knowledge and skills, required for designing digital systems. Furthermore, basic principles of components of a processor (CPU) are discussed as well as their relation. The processor is analysed based on the separation into a data- and control path. The operation and the structure of these paths will be discussed as well as the cooperation of the different components (e.g. the ALU, registers and busses). Besides that, attention will be paid to microprogramming (the basic principles are explained on the basis of different types of CPU’s) and to the Instruction Set Architecture (ISA), the link between software and hardware. Computer architecture concentrates on the processor and its environment. Students are taught the subsystems of which a computer system is constructed, how these subsystems behave and how they, together, determine the behaviour of the overall computer system. The design of elements within the memory hierarchy and I/O modules will be elaborated.
16	5	Operating Systems	An operating system is a resource manager; it basically ensures that all users get their fair share of the resources. The focus is on generic operating system concepts with illustrative examples from Linux wherever appropriate. Topics covered include the structure of the operating system, processes and threads, concurrency, deadlock and starvation, memory management, I/O management and file systems, access control, threats, protection and security. Students will be using mainly C and some Java.
17	5	ICT and Law	Computer scientists that have successfully finalized this course are capable of timely signalling the relevant IT-juridical aspects of their work and to fulfil their task to communicate on these aspects with legal professionals. As a first introduction into ICT and Law, focus is on three themes: legal protection of software (copyright, database right), protection of personal data (privacy law) and computer crime (criminal law).
18	6	Artificial Intelligence	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
19	6	Statistical Techniques	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
20	6	Human Computer Interaction	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
21	7	Discrete Structures & Algorithms	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
22	7	Algebra & Finite Automata	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
23	7	Research Project Graph Isomorphism	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
24	8	Functional Programming	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
25	8	Logic Programming	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
26	8	Compiler Construction	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
27	8	Concurrent Programming	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pulvinar odio neque, nec mattis nisi condimentum nec. Duis a nisi vel mi faucibus finibus nec et ligula. Etiam justo nulla, pharetra id vestibulum vel, molestie vel est. Maecenas arcu magna, malesuada quis lorem quis, semper vestibulum diam. Nam nec mauris at sem vehicula mollis vehicula vitae tortor. Maecenas finibus tristique velit, ac scelerisque ex. Suspendisse id egestas nibh. Vivamus id congue nisl. Duis sagittis, elit nec maximus ornare, nisl massa accumsan erat, non faucibus tellus mauris pellentesque nulla.
\.

COPY exercises (id, course_id, rights_template_id, name, description) FROM stdin;
1	1	1	Programming Exercise	A programming exercise for novice programmers.
2	2	1	Mathematics Tutorial	Show that P is equal to NP.
3	3	1	Programming Tutorial 3	Upload your solutions for the third programming tutorial here.
4	4	1	Programming Tutorial Homework	Upload your solutions to this week's programming tutorial here.
\.
